# Generated by Django 4.2.9 on 2024-02-04 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vlog', '0002_alter_vlogpost_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vlogpost',
            options={'ordering': ['-created'], 'permissions': [('can_publish', 'Может опубликовать')], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='vlogpost',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
    ]
