# Generated by Django 4.2.8 on 2024-01-13 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=10, verbose_name='номер версии')),
                ('version_name', models.CharField(max_length=200, verbose_name='название версии')),
                ('active_version', models.BooleanField(default=False, verbose_name='активная версия')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'версия продукта',
                'verbose_name_plural': 'версии продуктов',
                'ordering': ['version_number'],
            },
        ),
    ]
