# Generated by Django 4.2.8 on 2024-01-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_version_options_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.IntegerField(default=1, verbose_name='номер версии'),
        ),
    ]
